disabled_rules: # rule identifiers to exclude from running
  # - colon
  # - control_statement
  # - file_length
  # - force_cast
  # - function_body_length
  # - leading_whitespace
  - line_length
  # - nesting
  # - operator_whitespace
  # - return_arrow_whitespace
  # - todo
  # - trailing_newline
  # - trailing_whitespace
  # - type_body_length
  # - type_name
  # - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Main
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
variable_name:
  min_length:
    warning: 0
    error: 0
  excluded:
    - BASE_URL
    - ScaleX
    - ScaleY


